name: Owl Book CI Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: owlbarn/book:latest

    steps:
      - name: Checkout the book
        uses: actions/checkout@v2
        with:
          path: book-workflow

      - name: Create release tag
        id: create_release_tag
        working-directory: ./code
        if: ${{ contains(github.ref, 'master') }}
        run: |
          release_version=$(cat < package.json | jq -r .version)
          yarn version --new-version $release_version
          git tag $release_version
          git push --tags
          echo "APP_RELEASE_VERSION=$release_version" >> $GITHUB_ENV
          echo '::set-output name=app_release_version::'$release_version''

      - name: Compile the book
        working-directory: ./book-workflow
        run: |
          chown -R opam . &&
          su - opam -c 'export PATH=/home/opam/.cabal/bin:${PATH} && cd /__w/book/book/book-workflow && make compile'
          cd /__w/book/book/book-workflow
          date >> HISTORY.log

      - name: Save to the repository
        working-directory: ./book-workflow
        if: ${{ always() }}
        run: |
          git config user.name "owlbook_ci"
          git config user.email "ryanrhymes@gmail.com"
          git commit -am "[owlbook_ci] automated book compilation"
          git push

      - name: Checkout the website
        uses: actions/checkout@v2
        with:
          repository: owlbarn/owlbarn.github.io
          path: owlbarn.github.io
          token: ${{ secrets.OWLBOOK_CI_TOKEN }}

      - name: Update the website
        working-directory: owlbarn.github.io
        if: ${{ always() }}
        env:
          API_TOKEN_GITHUB: ${{ secrets.OWLBOOK_CI_TOKEN }}
        run: |
          git config user.name "owlbook_ci"
          git config user.email "ryanrhymes@gmail.com"
          cp /__w/book/book/book-workflow/docs/book.pdf _downloads/fb4b6b2df3a933e0d679dbb8a3f72ff9/book.pdf
          git commit -am "[owlbook_ci] automated book and website update"
          git push https://ryanrhymes:${API_TOKEN_GITHUB}@github.com/owlbarn/owlbarn.github.io/
